# Generated by Django 6.0.2 on 2026-02-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Марка машины'),
        ),
        migrations.AddField(
            model_name='user',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Модель машины'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('RUS', 'Россия 🇷🇺'), ('BLR', 'Беларусь 🇧y'), ('KAZ', 'Казахстан 🇰z')], default='RUS', max_length=3, verbose_name='Страна номера'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Имя пользователя (ФИО)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='license_plate',
            field=models.CharField(blank=True, max_length=15, verbose_name='Гос. номер'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+7', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateTimeField(verbose_name='Дата нарушения')),
                ('violation_type', models.CharField(max_length=50, verbose_name='Статья нарушения')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма штрафа')),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен')], default='unpaid', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(max_length=200, verbose_name='Место нарушения')),
                ('resolution_number', models.CharField(max_length=50, unique=True, verbose_name='Номер постановления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
                'ordering': ['-violation_date'],
            },
        ),
    ]
