# Generated by Django 6.0.2 on 2026-02-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_region',
            field=models.CharField(blank=True, max_length=3, verbose_name='Регион'),
        ),
    ]
