# Generated by Django 5.2.12 on 2026-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_vehicle_violation_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='accounts_ve_license_e62245_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='accounts_ve_owner_i_98eeee_idx',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, max_length=20, verbose_name='Категория ТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='Государственный номер'),
        ),
    ]
