# Generated by Django 5.2.13 on 2026-04-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_full_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='fine_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер постановления'),
        ),
    ]
