# Generated by Django 6.0.6 on 2026-06-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_violation_fine_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='violation_datetime',
            field=models.DateTimeField(blank=True, help_text='Укажите дату и время совершения нарушения', null=True, verbose_name='Дата и время нарушения'),
        ),
    ]
