# Generated by Django 6.0.2 on 2026-02-20 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_car_brand_user_car_model_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=15, verbose_name='Госномер ТС')),
                ('car_brand_model', models.CharField(max_length=100, verbose_name='Марка и модель ТС')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN номер')),
                ('article', models.CharField(max_length=100, verbose_name='Статья КоАП')),
                ('place', models.CharField(max_length=255, verbose_name='Место нарушения')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа (руб)')),
                ('evidence_img', models.ImageField(blank=True, null=True, upload_to='violations/', verbose_name='Фотофиксация')),
                ('description', models.TextField(blank=True, verbose_name='Дополнительные показания')),
                ('status', models.CharField(choices=[('fixed', 'Зафиксировано'), ('processed', 'Обработано'), ('fined', 'Вынесено постановление'), ('paid', 'Оплачено'), ('appealed', 'Обжаловано'), ('fssp', 'Передано в ФССП')], default='fixed', max_length=20, verbose_name='Статус')),
                ('fine_number', models.CharField(max_length=50, unique=True, verbose_name='Номер постановления')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_fines', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fines', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор')),
            ],
        ),
    ]
