# Generated by Django 6.0.3 on 2026-03-30 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_fine_id_alter_user_id_alter_violation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='date_time',
        ),
        migrations.AddField(
            model_name='user',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='violation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_categories',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_region',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='RUS', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Водитель'), ('inspector', 'Инспектор ДПС'), ('manager', 'Руководитель')], default='driver', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_id',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='vin_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='violation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='article',
            field=models.CharField(max_length=50, verbose_name='Статья КоАП'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='car_brand_model',
            field=models.CharField(max_length=255, verbose_name='Марка/модель'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='car_plate',
            field=models.CharField(max_length=20, verbose_name='Госномер'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='evidence_img',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='fine_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='violation',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('registered', 'Зарегистрировано'), ('paid', 'Оплачено'), ('appealed', 'Обжаловано')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN'),
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
