# Generated by Django 5.2.12 on 2026-04-07 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_violation_date_time_user_dismissed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_license_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия ВУ'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи ВУ'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AddField(
            model_name='violation',
            name='discount_until',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия скидки 50%'),
        ),
        migrations.AddField(
            model_name='violation',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='violation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_violation', 'Новое нарушение'), ('discount_expiring', 'Истекает срок скидки'), ('payment_reminder', 'Напоминание об оплате'), ('status_changed', 'Изменение статуса')], max_length=30, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.violation', verbose_name='Связанное нарушение')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('certificate', 'Справка о нарушениях'), ('detailed', 'Детальный отчет'), ('statistics', 'Статистический отчет')], max_length=20, verbose_name='Тип отчета')),
                ('date_from', models.DateField(verbose_name='Период с')),
                ('date_to', models.DateField(verbose_name='Период по')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data', models.JSONField(default=dict, verbose_name='Данные отчета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
