# Generated by Django 5.2.12 on 2026-04-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_driver_license_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCoAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50, unique=True, verbose_name='Номер статьи')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма штрафа (₽)')),
                ('penalty_points', models.IntegerField(default=0, verbose_name='Штрафные баллы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Статья КоАП',
                'verbose_name_plural': 'Статьи КоАП',
                'ordering': ['article_number'],
            },
        ),
    ]
