# Generated by Django 5.2.12 on 2026-04-07 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_violation_updated_at_alter_articlecoap_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Формат: А123ВС77', max_length=20, unique=True, verbose_name='Государственный номер')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN-номер')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('category', models.CharField(blank=True, choices=[('A', 'Мотоциклы'), ('B', 'Легковые автомобили'), ('C', 'Грузовые автомобили'), ('D', 'Автобусы'), ('E', 'Прицепы')], max_length=20, verbose_name='Категория ТС')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='violation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='accounts.vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='accounts_ve_license_e62245_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner'], name='accounts_ve_owner_i_98eeee_idx'),
        ),
    ]
