# Generated by Django 6.0.4 on 2026-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_vehicle_accounts_ve_license_e62245_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Статья КоАП')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма штрафа')),
            ],
        ),
    ]
