# Generated by Django 6.0.4 on 2026-04-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_finearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='car_region',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Регион'),
        ),
    ]
