# Generated by Django 6.0.4 on 2026-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_violation_car_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='car_region',
        ),
        migrations.AlterField(
            model_name='violation',
            name='car_plate',
            field=models.CharField(max_length=15, verbose_name='Госномер ТС'),
        ),
    ]
