# Generated by Django 6.0.4 on 2026-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_violation_car_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_license_plate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Госномер ТС'),
        ),
    ]
