# Generated by Django 6.0.6 on 2026-06-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_violation_violation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='inspector_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий инспектора'),
        ),
    ]
